version: '2'
services:

  api-gateway:
    container_name: api-gateway
    image: jwgwalton/ras-api-gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_NAME}
    networks:
      - rasdockerdev_default

  party-service:
    container_name: party-service
    image: jwgwalton/ras-party
    ports:
      - "${PARTY_PORT}:${PARTY_PORT}"
    environment:
      - ras-party-db.uri=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - oauth2-service.port=8040
      - oauth2-service.client_id=partyService@ons.gov
      - oauth2-service.client_secret=${PARTY_SERVICE_AUTH_SECRET}
    networks:
      - rasdockerdev_default

  secure-message-service:
    container_name: secure-message
    image: jwgwalton/ras-secure-message
    ports:
      - "${SECURE_MESSAGE_PORT}:${SECURE_MESSAGE_PORT}"
    environment:
      - SECURE_MESSAGING_DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
      - SM_JWT_ENCRYPT=0
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    networks:
      - rasdockerdev_default

  frontstage:
    container_name: frontstage
    image: jwgwalton/ras-frontstage
    ports:
      - "${FRONTSTAGE_PORT}:${FRONTSTAGE_PORT}"
    environment:
      -  API_GATEWAY_CASE_URL=http://localhost:8171/cases/
      -  API_GATEWAY_COLLECTION_EXERCISE_URL=http://localhost:8145/collectionexercises/
      -  API_GATEWAY_SURVEYS_URL=http://localhost:8080/surveys/
      -  API_GATEWAY_IAC_URL=http://localhost:8121/iacs/
      -  API_GATEWAY_COLLECTION_INSTRUMENT_URL=http://localhost:8082/collection-instrument-api/1.0.2/
      -  API_GATEWAY_AGGREGATED_SURVEYS_URL=http://localhost:8083/api/1.0.0/surveys/
      -  API_GATEWAY_PARTY_URL=http://localhost:8081/party-api/v1/
      -  OAUTHLIB_INSECURE_TRANSPORT=1
      -  ONS_OAUTH_PROTOCOL=http
      -  ONS_OAUTH_HOST=oauth2-service
      -  ONS_OAUTH_PORT=8040
      -  RAS_FRONTSTAGE_CLIENT_ID=frontstageService@ons.gov
      -  RAS_FRONTSTAGE_CLIENT_SECRET=${RAS_FRONTSTAGE_CLIENT_SECRET}
      -  RM_CASE_SERVICE_HOST=casesvc
      -  RM_CASE_SERVICE_PORT=8171
      -  RM_CASE_SERVICE_PROTOCOL=http
      -  RAS_COLLECTION_INSTRUMENT_SERVICE_HOST=collection-instrument
      -  RAS_COLLECTION_INSTRUMENT_SERVICE_PORT=8082
      -  RAS_COLLECTION_INSTRUMENT_SERVICE_PROTOCOL=http
      -  RAS_API_GATEWAY_SERVICE_HOST=localhost
      -  RAS_API_GATEWAY_SERVICE_PORT=8083
      -  RAS_API_GATEWAY_SERVICE_PROTOCOL=http
      -  RM_IAC_SERVICE_HOST=iac
      -  RM_IAC_SERVICE_PORT=8121
      -  RM_IAC_SERVICE_PROTOCOL=http
      -  RAS_PARTY_SERVICE_HOST=party-service
      -  RAS_PARTY_SERVICE_PORT=8081
      -  RAS_PARTY_SERVICE_PROTOCOL=http
      -  RM_COLLECTION_EXERCISE_SERVICE_HOST=collex
      -  RM_COLLECTION_EXERCISE_SERVICE_PORT=8145
      -  RM_COLLECTION_EXERCISE_SERVICE_PROTOCOL=http
      -  RM_SURVEY_SERVICE_HOST=survey
      -  RM_SURVEY_SERVICE_PORT=8085
      -  RM_SURVEY_SERVICE_PROTOCOL=http
      -  FS_DEV_PORT=5001
      -  SECURITY_USER_NAME=${SECURITY_USER_NAME}
      -  SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    networks:
      - rasdockerdev_default
      - rmdockerdev_default

  collection-instrument-service:
    container_name: collection-instrument
    image: jwgwalton/ras-collection-instrument
    ports:
      - "${COLLECTION_INSTRUMENT_PORT}:${COLLECTION_INSTRUMENT_PORT}"
    environment:
      - db_port=${POSTGRES_PORT}
      - API_GATEWAY_CASE_URL=http://localhost:8171/cases/
      - API_GATEWAY_COLLECTION_EXERCISE_URL=http://localhost:8145/collectionexercises/
      - API_GATEWAY_SURVEY_SERVICE_URL=http://localhost:8080/surveys/
      - RABBITMQ_AMQP=amqp://guest:guest@localhost:6672
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    networks:
      - rasdockerdev_default

  backstage:
    container_name: backstage
    image: jwgwalton/ras-backstage
    ports:
      - "${BACKSTAGE_PORT}:${BACKSTAGE_PORT}"
    environment:
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    networks:
      - rasdockerdev_default

networks:
   rasdockerdev_default:
     external: true
   rmdockerdev_default:
     external: true
